### ISSUE TITLE
VITS paper ?

### ISSUE THREAD

**Issue by rishikksh20** [jaywalnut310/vits#1]
@jaywalnut310 I am unable to find the paper on which this repo based on.

**Comment by jaywalnut310** [comment]
@rishikksh20 Thanks for you interest! The paper will be uploaded on arxiv after a couple of days (if no problem arises). When it's uploaded, I'll update README and make a link to it. Please wait until then :).

**Comment by rishikksh20** [comment]
Great!!!

**Comment by jaywalnut310** [comment]
Now the paper is available: https://arxiv.org/abs/2106.06103

**Comment by rishikksh20** [comment]
@jaywalnut310 thanks. I set-up collab for LJ-Speech : https://colab.research.google.com/drive/1aNMn2PHDzhQ2nFU5RoWsPSjesDeedm5B?usp=sharing

**Comment by jaywalnut310** [comment]
> @jaywalnut310 thanks. I set-up collab for LJ-Speech : https://colab.research.google.com/drive/1aNMn2PHDzhQ2nFU5RoWsPSjesDeedm5B?usp=sharing

@rishikksh20 Thans for your amazing work! Is it okay to introduce your collab in README?
It would be much grateful, if your sentence of the last line is like "We propose VITS, a Conditional Variational Autoencoder with Adversarial Learning for End-to-End Text-to-Speech."

**Comment by rishikksh20** [comment]
Yeah Sure, I have update the collab notebook.

**Comment by jaywalnut310** [comment]
@rishikksh20 Based on your work, I made a new notebook including multi speaker examples. Thanks again for your work, and I referred you in README!

**Comment by ikcla** [comment]
Thank you for your great works. Is it possible to resume/finetune training from your pretrain checkpoint? In the code, I saw checkpoints were saved to model_dir with two file -G (generator) and -D (discriminator), but provided data only one pretrain file.  Thanks.

**Comment by SameerSri72** [comment]
@rishikksh20 sir your colab notebook is not running smoothly due to version mismatch. while installing requirements encounters error in generating package metadata.
And !python setup.py build_ext --inplace is not able to create necessary core.cpython file.
with my limited understanding I modified certain parts of your notebook and it is working upto "Multi speaker" section.
please have a look 
https://colab.research.google.com/drive/1Sz6OW25WXPIhuEElgAFy77o98YOdhx7a?usp=sharing

if these changes are acceptable then you can modify the notebook for the benefit of everybody.
For a newbie like me any feedback/suggestion will mean a lot.
FYI @jaywalnut310
